name: PDF to Word Conversion

on:
  repository_dispatch:
    types: [pdf_conversion]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Convert PDF to Word
      env:
        INPUT_FILE: ${{ github.event.client_payload.filename }}
        INPUT_CONTENT: ${{ github.event.client_payload.content }}
      run: |
        # Save the input file
        echo "$INPUT_CONTENT" | base64 --decode > input.pdf
        
        # Convert to Word
        python convert.py input.pdf output.docx
        
        # Upload artifact
        echo "CONVERTED_FILE=output.docx" >> $GITHUB_ENV
        
    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: converted-word-file
        path: output.docx
