name: PDF to Word Conversion

on:
  repository_dispatch:
    types: [pdf_conversion]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PDF_CONVERTER_TOKEN }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install pdf2docx==0.5.7
        pip install PyGithub==1.58.2
        
    - name: Create input PDF
      env:
        INPUT_CONTENT: ${{ github.event.client_payload.content }}
      run: |
        echo "$INPUT_CONTENT" | base64 --decode > input.pdf
        echo "PDF size: $(du -h input.pdf | cut -f1)"
        
    - name: Convert PDF to Word
      run: |
        python convert.py input.pdf output.docx
        
    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: converted-word-file
        path: output.docx
        retention-days: 1
