name: PDF to Word Conversion

on:
  repository_dispatch:
    types: [pdf_conversion]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdf2docx==0.5.7
        
    - name: Create input PDF
      env:
        INPUT_CONTENT: ${{ github.event.client_payload.content }}
      run: |
        echo "$INPUT_CONTENT" | base64 --decode > input.pdf
        echo "PDF size: $(du -h input.pdf | cut -f1)"
        
    - name: Convert PDF to Word
      id: convert
      run: |
        python convert.py input.pdf output.docx
        echo "DOCX size: $(du -h output.docx | cut -f1)"
        echo "converted=output.docx" >> $GITHUB_OUTPUT
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: converted-docx
        path: ${{ steps.convert.outputs.converted }}
        retention-days: 1
        
    - name: Create download URL
      run: |
        echo "Download URL: https://github.com/$GITHUB_REPOSITORY/releases/download/conversion/output.docx"
